```{r, echo=FALSE, message=FALSE, include=FALSE}
if (!requireNamespace("pacman")) install.packages("pacman")
packages_cran <- c("here")
pacman::p_load(char = packages_cran)
if (basename(here::here()) == "highspeed"){
  path_root = here::here("highspeed-glm")
} else {
  path_root = here::here()
}
```

## Feature selection: First-level GLMs

### Overview

As described above, we used a feature selection approach that combined binarized anatomical ROIs with functional ROIs based on first-level GLMs.
Below we show which code was used to run the first-level GLMs based on Nipype:

#### Data availability

The data is freely available from https://github.com/lnnrtwttkhn/highspeed-glm and https://gin.g-node.org/lnnrtwttkhn/highspeed-glm.

#### License

The dataset is licensed under Creative Commons Attribution-ShareAlike 4.0.
Please see https://creativecommons.org/licenses/by-sa/4.0/ for details.

### Main GLM workflow (`highspeed-glm-main.py`)

The code below shows the main Nipype workflow to run first-level GLMs used for feature selection:

```{python, echo=TRUE, code=readLines(file.path(path_root, "code", "glm", "highspeed-glm-main.py")), eval=FALSE, python.reticulate=FALSE}
```

### Extra GLM functions (`highspeed-glm-functions.py`)

The main GLM Nipype workflow shown above uses the following custom functions:

```{python, echo=TRUE, code=readLines(file.path(path_root, "code", "glm", "highspeed_glm_functions.py")), eval=FALSE, python.reticulate=FALSE}
```

### Software: Required packages

The `requirements.txt` file lists the required packages which can be installed e.g., using `pip install -r requirements.txt`

```{bash, echo=TRUE, code=readLines(file.path(path_root, "code", "glm", "requirements.txt")), eval=FALSE}
```
